config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
  resources :forecasts, only: %i[ show ], param: :zip_code, constraints: { zip_code: /\d{5}/ } do
    get "content", on: :member
  end
end

app/models/forecast.rb
class Forecast

  CACHE_EXPIRATION = 30.minutes

  include ActiveModel::API
  include ActiveModel::Attributes

  attribute :city, :string
  attribute :current_temp, :integer
  attribute :current_weather, :string
  attribute :fetched_at, :datetime
  attribute :forecast_periods
  attribute :high_temp, :integer
  attribute :low_temp, :integer
  attribute :zip_code, :string

  def self.cache_key(zip_code)
    "forecast-#{zip_code}"
  end

  def self.fetch(zip_code, lat, lon, city)
    Rails.cache.fetch(cache_key(zip_code), expires_in: CACHE_EXPIRATION) do
      fetch_from_nws(zip_code, lat, lon, city)
    end
  end

  def self.fetch_from_nws(zip_code, lat, lon, city)
    new(zip_code: zip_code, city: city).fetch_from_nws(lat, lon)
  end

  def cache_key
    "forecast-#{zip_code}"
  end

  def fetch_from_nws(lat, lon)

    # Make sure we're calling this on a properly initialized object.
    raise ArgumentError, "`city` is required" if city.blank?
    raise ArgumentError, "`zip_code` is required" if zip_code.blank?

    # The NWS API requires the lat/lon only has four decimal places. So,
    # we round them here.
    lat = lat.round(4)
    lon = lon.round(4)

    # Use the NWS API to look up the forecast for the lat/lon pair. This
    # first call doesn't contain the forecast, but it does contain URLs
    # to other resources that contain the forecast.
    points_response = Faraday.get("https://api.weather.gov/points/#{lat},#{lon}")
    points_response_body = JSON.parse(points_response.body)

    # To get the current temperature, we need to find the URL for a
    # weather station. This is a two step process. First, we get the
    # URL for the observation stations near the lat/lon pair.
    observation_stations_url = points_response_body["properties"]["observationStations"]

    observation_stations_response = Faraday.get(observation_stations_url)
    observation_stations_response_body = JSON.parse(observation_stations_response.body)

    # Then, we get the URL for the actual weather station. We'll use the
    # first one in the list. If we were a clever clogs, we'd fetch a few
    # and maybe interpolate between them.
    #
    # Strangely, we need to manually create the URL for the latest
    # observations as it's not provided in the response, unlike
    # everywhere else.
    station_id = observation_stations_response_body["features"][0]["properties"]["stationIdentifier"]
    station_latest_observations_url = "https://api.weather.gov/stations/#{station_id}/observations/latest"

    # Get the latest observations from the weather station.
    station_latest_observations_response = Faraday.get(station_latest_observations_url)
    station_latest_observations_response_body = JSON.parse(station_latest_observations_response.body)

    # The current temperature is in the response in Celsius. We'll
    # convert it to Fahrenheit.
    current_temp_in_c = station_latest_observations_response_body["properties"]["temperature"]["value"]
    current_temp_in_f = (current_temp_in_c * 9 / 5) + 32
    self.current_temp = current_temp_in_f.round

    # There's also a nice text description of the current weather conditions.
    self.current_weather = station_latest_observations_response_body["properties"]["textDescription"]

    # I was told there's bonus points for getting the seven day
    # forecast, so we'll get that here.
    forecast_url = points_response_body["properties"]["forecast"]

    # Get the forecast for the next 7 days.
    forecast_response = Faraday.get(forecast_url)
    forecast_response_body = JSON.parse(forecast_response.body)

    # We'll print out the data basically as delivered from the API.
    forecast_periods = forecast_response_body["properties"]["periods"]
    self.forecast_periods = forecast_periods.map do |period|
      ForecastPeriod.from_nws_api_json(period)
    end

    # It's a little ambiguous what "high" and "low" mean in the
    # forecast. I'm going to assume it's the high and low for the next
    # two forecast periods adjusted with the current temperature.
    forecast_and_current_temps = forecast_periods.take(2).pluck("temperature") + [current_temp_in_f]
    self.high_temp = forecast_and_current_temps.max
    self.low_temp = forecast_and_current_temps.min

    self.fetched_at = Time.current

    self
  end

  def newly_fetched?
    (fetched_at > 1.minute.ago) if fetched?
  end

  def fetched?
    fetched_at.present?
  end

  def to_key
    zip_code.present? ? [zip_code] : nil
  end

  def to_param
    zip_code
  end
end

app/models/forecast_period.rb
class ForecastPeriod
  include ActiveModel::API
  include ActiveModel::Attributes

  attribute :name, :string
  attribute :temperature, :float
  attribute :precipitation_probability, :integer
  attribute :short_forecast, :string

  def self.from_nws_api_json(period_json)
    new(
      name: period_json["name"],
      temperature: period_json["temperature"],
      precipitation_probability: period_json["probabilityOfPrecipitation"]["value"] || 0,
      short_forecast: period_json["shortForecast"])
  end
end

app/models/geocoder.rb
class Geocoder

  CACHE_EXPIRATION = 24.hours
  class FailedGeocode < StandardError; end

  class Result
    attr_reader :lat
    attr_reader :lng
    attr_reader :city
    attr_reader :zip_code

    def self.from_geokit_results(results)
      new(results.lat, results.lng, results.city, results.zip)
    end

    def initialize(lat, lng, city, zip_code)
      @lat = lat
      @lng = lng
      @city = city
      @zip_code = zip_code
    end
  end

  def self.cache_key(zip_code)
    "geocoder-#{zip_code}"
  end

  def self.geocode(query)
    Rails.cache.fetch(cache_key(query.zip_code), expires_in: CACHE_EXPIRATION) do
      geocode_with_geokit(query)
    end
  rescue
    Rails.cache.delete(cache_key(query.zip_code))
    raise FailedGeocode
  end

  def self.geocode_with_geokit(query)
    results = Geokit::Geocoders::GeocodioGeocoder.geocode(query.q)
    puts results.inspect
    # If the geocode fails to provide a ZIP code, or fails entirely we
    # consider it a failure.
    raise FailedGeocode unless results.success? && results.zip.present?
    Geocoder::Result.from_geokit_results(results)
  end
end

app/models/query.rb
class Query
  include ActiveModel::API
  include ActiveModel::Attributes

  attribute :q, :string

  validate do
    unless city_and_state? || zip_code?
      errors.add(:base, "must be a valid ZIP code or city and state")
    end
  end

  def provided?
    q.present?
  end

  def zip_code
    q&.squish
  end

  private

  def city_and_state?
    q.present? && q.squish.match?(/\A(\S+\s*)+[ ,][A-Z]{2}\z/i)
  end

  def zip_code?
    q.present? && q.squish.match?(/\A\s*\d{5}\z/)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  def show
    query = Query.new(q: params[:zip_code])
    # Use Geocoder to geocode the ZIP code. The NWS API needs a lat/lng
    # pair to look up the forecast.
    result = Geocoder.geocode(query)
    @forecast = Forecast.new(zip_code: result.zip_code, city: result.city)
  end

  def content
    query = Query.new(q: params[:zip_code])
    # Use Geocoder to geocode the ZIP code. The NWS API needs a lat/lng
    # pair to look up the forecast.
    result = Geocoder.geocode(query)
    @forecast = Forecast.fetch(result.zip_code, result.lat, result.lng, result.city)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @query = Query.new(q: params[:q])
    if @query.valid?
      result = Geocoder.geocode(@query)
      redirect_to forecast_path(result.zip_code)
    else
      flash[:alert] = "Please enter a valid ZIP code or city and state."
      render :index
    end
  rescue Geocoder::FailedGeocode
    flash[:alert] = "We couldn't find \"#{params[:q].squish}\". Please try again with a valid ZIP code or city and state."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_nil_as_dashes(value)
    value.nil? ? "--".html_safe : value
  end
end

app/views/forecast_periods/_forecast_period.html.erb
<tr class="forecast_period">
  <th><%= forecast_period.name %></th>
  <td class="text-end"><%= forecast_period.temperature %>&deg;</td>
  <td class="text-end"><%= forecast_period.precipitation_probability %>%</td>
  <td class="d-none d-md-block"><%= forecast_period.short_forecast.capitalize %></td>
</tr>

app/views/forecasts/_forecast.html.erb
<section class="text-center my-5">
  <h1 class="mb-0"><%= forecast.city %></h1>
  <h1 id="current_temp", class="display-1 fw-lighter mt-0"><%= format_nil_as_dashes(forecast.current_temp) %>&deg;</h1>
  <p class="lead mb-0"><%= format_nil_as_dashes(forecast.current_weather) %></p>
  <p class="lead">H:<%= format_nil_as_dashes(forecast.high_temp) %>&deg; L:<%= format_nil_as_dashes(forecast.low_temp) %>&deg;</p>
  <% if forecast.fetched? && !forecast.newly_fetched? %>
    <div class="alert alert-light text-center my-4" role="alert">
      <i>Forecast data was updated <%= time_ago_in_words(forecast.fetched_at) %> ago.</i>
    </div>
  <% end %>
</section>
<% if forecast.forecast_periods.present? %>
  <section class="my-4">
    <h5>7-day Forecast</h5>
    <table id="forecast_periods" class="table table-borderless my-4">
      <thead>
      <th></th>
      <th class="text-end">🌡️</th>
      <th class="text-end">🌧️</th>
      <th class="d-none d-md-block"></th>
      </thead>
      <tbody>
      <%= render forecast.forecast_periods %>
      </tbody>
    </table>
  </section>
<% end %>

app/views/forecasts/content.html.erb
<%= turbo_frame_tag(@forecast) do %>
  <%= render @forecast %>
<% end %>

app/views/forecasts/show.html.erb
<%= turbo_frame_tag(@forecast, src: content_forecast_path(@forecast)) do %>
  <%= render @forecast %>
<% end %>

app/views/home/index.html.erb
<% if @query.provided? && flash.key?(:alert) %>
  <div class="alert alert-danger">
    <span><%= flash[:alert] %></span>
  </div>
<% end %>

<%= form_tag("/", method: :get, class: %w[ d-flex ]) do %>
  <%= text_field_tag(:q, params[:q], class: %w[ form-control me-2 ], placeholder: "Search City or Zip Code") %>
  <%= submit_tag("Lookup", class: %w[ btn btn-outline-secondary ]) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Greysky</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>

    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-white mb-5">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">🌥️Greysky</a>
        </div>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>